online-mode=false
server-ip=127.0.0.1
server-port=0
level-type=minecraft:flat
generator-settings={"layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:dirt","height":2},{"block":"minecraft:grass_block","height":1}],"biome":"minecraft:plains"}
generate-structures=false
view-distance=2
simulation-distance=2
spawn-protection=0
max-players=1
sync-chunk-writes=false
